# Generated by Django 4.2.6 on 2023-11-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_employees_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='images',
        ),
        migrations.AddField(
            model_name='employees',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
